members:
  - U7ZD2FCBB
  - U95LN062K
  - UCJA2A8Q5
  - UB348CP6Z
  - U83UZCDCM
  - UAXAVEF3M
  - UB4J7597H
  - UC7FJCL9G
  - UB2ELL480
  - UAWNQHH38
  - U89DXTF6W
  - UASHT1H7U
  - UBV9QPYP9
  - UCS9EMKG9
  - U90418USW
  - UATDAFP9T
  - UCV6RPQRL
  - UCLFL0K2A
  - UD65U3S1H
  - UCVTS7KPU
admins:
  - UB348CP6Z
  - UCJA2A8Q5
