  eslint:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
